[connections.mysql]
dialect = "mysql"
host = "db-mysql-blr1-56656-do-user-17670244-0.l.db.ondigitalocean.com"
port = 25060
database = "Certificate_db"
username = "dev_team"
password = "AVNS_uJ-IuLOm7oT3gh1QqTm"
[connections.mysql.query]
charset = "utf8mb4"